// schemas/fullMoon.js
export default {
  name: 'fullMoon',
  title: 'Full Moon',
  type: 'document',
  fields: [
    {
      name: 'year',
      title: 'Year',
      type: 'number',
      validation: Rule => Rule.required().min(2020).max(2030)
    },
    {
      name: 'month',
      title: 'Month',
      type: 'number',
      validation: Rule => Rule.required().min(1).max(12)
    },
    {
      name: 'date',
      title: 'Full Moon Date',
      type: 'datetime',
      validation: Rule => Rule.required()
    },
    {
      name: 'name',
      title: 'Traditional Name',
      type: 'string',
      description: 'e.g., Wolf Moon, Snow Moon, Harvest Moon'
    },
    {
      name: 'sign',
      title: 'Zodiac Sign',
      type: 'string',
      options: {
        list: [
          'Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo',
          'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'
        ]
      }
    },
    {
      name: 'peakTime',
      title: 'Peak Time (UTC)',
      type: 'string',
      description: 'Format: HH:MM'
    },
    {
      name: 'intensity',
      title: 'Energy Intensity',
      type: 'string',
      options: {
        list: [
          { title: 'Gentle', value: 'gentle' },
          { title: 'Moderate', value: 'moderate' },
          { title: 'Intense', value: 'intense' }
        ]
      }
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text'
    },
    {
      name: 'energy',
      title: 'Energy Theme',
      type: 'string'
    },
    {
      name: 'themes',
      title: 'Key Themes',
      type: 'array',
      of: [{ type: 'string' }]
    },
    {
      name: 'isEclipse',
      title: 'Is Lunar Eclipse',
      type: 'boolean',
      initialValue: false
    },
    {
      name: 'autoGenerated',
      title: 'Auto Generated',
      type: 'boolean',
      readOnly: true,
      initialValue: false
    }
  ],
  preview: {
    select: {
      name: 'name',
      year: 'year',
      sign: 'sign',
      date: 'date'
    },
    prepare(selection) {
      const { name, year, sign, date } = selection;
      const formattedDate = new Date(date).toLocaleDateString();
      return {
        title: `${name} ${year}`,
        subtitle: `${sign} - ${formattedDate}`
      };
    }
  }
};