// schemas/mercuryRetrograde.js
export default {
  name: 'mercuryRetrograde',
  title: 'Mercury Retrograde',
  type: 'document',
  fields: [
    {
      name: 'year',
      title: 'Year',
      type: 'number',
      validation: Rule => Rule.required().min(2020).max(2030)
    },
    {
      name: 'phase',
      title: 'Phase Number',
      type: 'number',
      validation: Rule => Rule.required().min(1).max(4)
    },
    {
      name: 'startDate',
      title: 'Start Date',
      type: 'datetime',
      validation: Rule => Rule.required()
    },
    {
      name: 'endDate',
      title: 'End Date', 
      type: 'datetime',
      validation: Rule => Rule.required()
    },
    {
      name: 'preRetrograde',
      title: 'Pre-Retrograde Shadow Start',
      type: 'datetime'
    },
    {
      name: 'postRetrograde',
      title: 'Post-Retrograde Shadow End',
      type: 'datetime'
    },
    {
      name: 'sign',
      title: 'Zodiac Sign',
      type: 'string',
      options: {
        list: [
          'Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo',
          'Libra', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'
        ]
      }
    },
    {
      name: 'intensity',
      title: 'Intensity Level',
      type: 'string',
      options: {
        list: [
          { title: 'Low', value: 'low' },
          { title: 'Medium', value: 'medium' },
          { title: 'High', value: 'high' }
        ]
      }
    },
    {
      name: 'description',
      title: 'Description',
      type: 'text'
    },
    {
      name: 'effects',
      title: 'Key Effects',
      type: 'array',
      of: [{ type: 'string' }]
    },
    {
      name: 'autoGenerated',
      title: 'Auto Generated',
      type: 'boolean',
      readOnly: true,
      initialValue: false
    }
  ],
  preview: {
    select: {
      year: 'year',
      phase: 'phase',
      sign: 'sign',
      startDate: 'startDate'
    },
    prepare(selection) {
      const { year, phase, sign, startDate } = selection;
      const date = new Date(startDate).toLocaleDateString();
      return {
        title: `${year} Phase ${phase} - ${sign}`,
        subtitle: `Starts: ${date}`
      };
    }
  }
};
