// AUTO-GENERATED by utils/generate-articles-manifest.mjs — DO NOT EDIT BY HAND.
// Regenerate with: npm run generate-articles

export interface ArticleMeta {
  _id: string;
  _type: 'article';
  source: 'sanity' | 'static';
  slug: { current: string };
  title: string;
  publishDate: string;
  tags: string[];
  metaDescription?: string;
  mainImage?: any;
  mainImageUrl?: string;
  mainImageAlt?: string;
}

export const ARTICLES: ArticleMeta[] = [
  {
    "_id": "sanity-hungry-ghost-month-2026-survival-guide",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "hungry-ghost-month-2026-survival-guide"
    },
    "title": "Hungry Ghost Month 2026: What Opens the Gates, What Walks Through, and How to Survive It (Aug 13 – Sep 10)",
    "publishDate": "2026-05-25T06:45:00.000Z",
    "tags": [
      "Hungry Ghost Month",
      "Ghost Festival 2026",
      "Feng Shui Protection",
      "Chinese Traditions",
      "Spiritual Protection",
      "Year of the Fire Horse",
      "Taboos and Superstitions",
      "Lunar Calendar",
      "Feng Shui"
    ],
    "metaDescription": "Ghost Month 2026 runs August 13–September 10. Discover the ancient origins behind the opened \"Gates of Hell,\" the taboos you shouldn't break, and feng shui protection tips to survive unscathed.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-9ba348d634f771f351d1fff9047b227f5a1eef84-4330x2845-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "static-celebrity-birthdays",
    "_type": "article",
    "source": "static",
    "slug": {
      "current": "famous-celebrity-birthdays"
    },
    "title": "Famous Celebrity Birthdays & Their Zodiac Signs",
    "publishDate": "2026-05-25",
    "tags": [
      "Celebrity"
    ],
    "metaDescription": "Explore famous celebrity birthdays organized by month. Discover the Western zodiac signs and Chinese zodiac animals of your favorite stars.",
    "mainImageUrl": "/celebrity-birthdays.jpg",
    "mainImageAlt": "Famous celebrity birthdays and zodiac signs"
  },
  {
    "_id": "static-number-33",
    "_type": "article",
    "source": "static",
    "slug": {
      "current": "the-number-33"
    },
    "title": "The Number 33: Elite Obsession, Hidden Patterns, or a Trick of Your Mind?",
    "publishDate": "2026-05-24",
    "tags": [
      "Numerology"
    ],
    "metaDescription": "Why does the number 33 appear everywhere—from Freemasonry to the human spine to world-changing events? Explore the conspiracies, the coincidences, and the psychological trick that might explain it all.",
    "mainImageUrl": "/the-number-33.jpg",
    "mainImageAlt": "Glowing numerology artwork featuring the number 33"
  },
  {
    "_id": "sanity-2026-numerology-universal-year-1-global-reset",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "2026-numerology-universal-year-1-global-reset"
    },
    "title": "2026 Numerology: Why This \"Universal Year 1\" Is Your Ultimate Global Reset",
    "publishDate": "2026-02-23T02:00:01.501Z",
    "tags": [
      "Universal Year 1",
      "Global Reset 2026",
      "Year of the Fire Horse",
      "Spirituality and New Beginnings",
      "Manifestation 2026",
      "Personal Year Calculation",
      "Numerology"
    ],
    "metaDescription": "Discover why 2026 is the Universal Year 1 in Numerology. Learn how this \"Global Reset\" brings new beginnings, independence, and the perfect energy for a fresh start after the chaos of 2025.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-bfd1eca02f32b5b4a0a93155c289e1ce7a389b28-4928x3264-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-feng-shui-2026-lucky-colors-symbols-zodiac-forecast",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "feng-shui-2026-lucky-colors-symbols-zodiac-forecast"
    },
    "title": "2026 Feng Shui: Lucky Colors, Symbols & Zodiac Forecast",
    "publishDate": "2025-12-13T05:30:31.445Z",
    "tags": [
      "feng shui 2026",
      "lucky colors 2026",
      "feng shui symbols",
      " chinese zodiac 2026",
      "zodiac forecast 2026",
      "feng shui remedies",
      "auspicious symbols",
      "feng shui amulets",
      "year of horse 2026",
      "zodiac compatibility 2026",
      "chinese"
    ],
    "metaDescription": "Discover your 2026 zodiac forecast, lucky colors, and powerful Feng Shui symbols. Complete guide to remedies, timing strategies, and protective amulets.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-9982917b499cdf7fb052bca4a012992b0425bc62-6000x4000-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-flying-stars-2026-feng-shui-sector-guide",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "flying-stars-2026-feng-shui-sector-guide"
    },
    "title": "Flying Stars 2026: Complete Feng Shui Sector Guide",
    "publishDate": "2025-12-09T16:30:26.435Z",
    "tags": [
      "flying stars 2026",
      "feng shui 2026",
      "xuan kong feng shui",
      "annual feng shui stars",
      "feng shui sectors 2026",
      "feng shui cures 2026",
      "star 5 remedy",
      "star 9 activation",
      "flying star chart",
      "feng shui directions 2026",
      "feng shui"
    ],
    "metaDescription": "Complete Flying Stars 2026 guide. Learn which sectors bring luck or challenges, with detailed remedies and activation tips for each of the nine star positions.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-1bebe5725f9d4c9bee13767441c83dd30331fbee-6000x4000-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-feng-shui-2026-year-of-fire-horse",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "feng-shui-2026-year-of-fire-horse"
    },
    "title": "Feng Shui 2026: Year of Fire Horse Overview & Energy Guide",
    "publishDate": "2025-12-08T17:00:34.117Z",
    "tags": [
      "feng shui 2026",
      "year of fire horse",
      "feng shui",
      "fire horse energy",
      "chinese astrology 2026",
      "water element missing",
      "feng shui forecast",
      "fire horse year",
      "yang fire horse",
      "elemental analysis 2026"
    ],
    "metaDescription": "Discover what the Year of Fire Horse 2026 means for you. Learn about the double Fire energy, missing Water element, and how to balance the five elements.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-9d8e9f2d17250235e5b7ff12856ae55800bec6c1-1376x768-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-october-2025-horoscope-zodiac-forecast",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "october-2025-horoscope-zodiac-forecast"
    },
    "title": "Your Cosmic Forecast: October 2025 Horoscope & Astrological Guide",
    "publishDate": "2025-10-09T11:30:06.736Z",
    "tags": [
      "western",
      "October 2025 Horoscope",
      "October Astrology",
      "Libra Season",
      "Scorpio Season",
      "Full Moon in Aries",
      "New Moon in Libra",
      "Zodiac Forecast",
      "Western Zodiac"
    ],
    "metaDescription": "Dive into your October 2025 horoscope! Discover how the Aries Full Moon and the Libra New Moon will transform your love life, career, and destiny this Libra Season.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-e3ddfd78bb7724e8d2a24203ffd24fe5e53c2912-4000x6000-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-mid-autumn-festival-guide",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "mid-autumn-festival-guide"
    },
    "title": "Mid-Autumn Festival: Full Moon, Mooncakes & Family",
    "publishDate": "2025-10-05T15:15:57.958Z",
    "tags": [
      "Mid-Autumn Festival",
      "Mooncake Festival",
      "Chinese holiday",
      "family reunion",
      "mooncakes",
      "Chinese culture",
      "harvest festival",
      "full moon",
      "Chang'e"
    ],
    "metaDescription": "Discover the Mid-Autumn Festival (Mooncake Festival) traditions. Learn why families celebrate the brightest full moon and the harvest as they gather to share symbolic mooncakes.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-903c7653f5aae5982a93256d57afe3d8934f0d85-2848x4104-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-feng-shui-astrology-for-october-2025",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "feng-shui-astrology-for-october-2025"
    },
    "title": "October 2025 Feng Shui Astrology & Luck Boost",
    "publishDate": "2025-10-05T00:30:17.584Z",
    "tags": [
      "feng shui",
      "october 2025",
      "flying stars",
      "home harmony",
      "wealth",
      "chinese zodiac",
      "luck boost",
      "simple feng shui",
      "latest feng shui forecast"
    ],
    "metaDescription": "Use the Flying Stars to navigate October 2025! Discover where to find wealth (North) and dodge trouble (Southwest). Quick, fun tips to harmonize your home and boost your luck this month.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-34f4aaf5304ceb7611729f1d2809eabcbff3f4da-2923x3897-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-chinese-zodiac-hilarious-roast",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "chinese-zodiac-hilarious-roast"
    },
    "title": "Chinese Zodiac Roast: Your Sign's Hilarious Truth",
    "publishDate": "2025-09-24T16:15:12.872Z",
    "tags": [
      "Chinese Zodiac",
      "Zodiac Roast",
      "Chinese Astrology",
      "Animal Signs",
      "Funny Zodiac",
      "Chinese New Year",
      "Humor",
      "Zodiac Personality",
      "What's My Chinese Zodiac",
      "Chinese Horoscope Fun",
      "chinese"
    ],
    "metaDescription": "Ever wondered what the Chinese Zodiac really says about you? Get ready for a brutally honest and hilarious roast of all 12 animal signs. Discover your quirky truths and laugh along!",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-d62e113a8c3fb3b211a38fec911511fa18b90d05-6000x4000-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-astrology-101-complete-beginners-guide",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "astrology-101-complete-beginners-guide"
    },
    "title": "Astrology 101: Complete Beginner's Guide to Birth Charts",
    "publishDate": "2025-09-19T05:00:19.712Z",
    "tags": [
      "astrology 101",
      "how to read your birth chart for beginners",
      "what do houses mean in astrology",
      "astrology for beginners",
      "difference between sun moon and rising signs",
      "complete guide to understanding astrology basics",
      "planetary aspects in astrology explained simply",
      "astrology houses and their meanings beginner guide",
      "western"
    ],
    "metaDescription": "Learn astrology basics: birth charts, zodiac signs, planets & houses explained. Complete beginner's guide to understanding your astrological profile and cosmic influences.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-f6e020486d77fda2014f5ff37d951c7bd77e8130-8192x4040-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-universal-number-9-september-numerology",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "universal-number-9-september-numerology"
    },
    "title": "The Universal Number 9: September's Energetic Endings",
    "publishDate": "2025-09-13T16:15:00.978Z",
    "tags": [
      "Numerology",
      "Universal Number 9",
      "999 portal",
      "September numerology",
      "completion",
      "closure",
      "spiritual awakening",
      "numerology 2025",
      "personal growth",
      "numerology"
    ],
    "metaDescription": "Discover the powerful numerology of September's Universal Number 9. Learn how this energy of completion and closure helps you release the past and prepare for new beginnings.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-7dcc9f6259f2b05c95e2150126889a373f0c46de-3872x2592-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-feng-shui-traditional-vs-modern",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "feng-shui-traditional-vs-modern"
    },
    "title": "Traditional vs. Modern Feng Shui: What’s the Difference?",
    "publishDate": "2025-09-12T03:00:16.681Z",
    "tags": [
      "Feng Shui",
      "traditional Feng Shui",
      "modern Feng Shui",
      "Bagua",
      "five elements",
      "home decor",
      "interior design",
      "space harmony",
      "energy flow",
      "Chinese art"
    ],
    "metaDescription": "Unlock the secrets of Feng Shui! Explore the differences between traditional practices using natural elements and modern \"cures\" like money toads. Find out what's right for your home.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-51e83bb4380273dca09873f0cbbee7f8c90d3b8f-1000x1500-png",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-astrology-roast-zodiac-signs",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "astrology-roast-zodiac-signs"
    },
    "title": "Your Zodiac Sign, But It's a Hilarious Roast",
    "publishDate": "2025-09-05T05:15:54.088Z",
    "tags": [
      "astrology",
      "zodiac signs",
      "horoscope",
      "funny",
      "roast",
      "personality",
      "horoscopes",
      "star  signs",
      "western zodiac"
    ],
    "metaDescription": "Are you ready to face the music? We're hilariously roasting all 12 zodiac signs, from Aries to Pisces. Get ready to laugh at yourself (and your friends).",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-83f28970a2de84240aae7856a1d7a732bf9445e0-3936x2624-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-dating-by-elements",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "dating-by-elements"
    },
    "title": "Dating by the Elements",
    "publishDate": "2025-09-02T16:15:00.000Z",
    "tags": [
      "Dating by the elements",
      "Five Elements",
      "Yin and Yang",
      "Love & Dating",
      "Personality Types",
      "element"
    ],
    "metaDescription": "Explore Feng Shui’s Five Elements in love—find out if you click better with Yin Fire’s warmth, Yang Metal’s strength, or another element altogether.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-69e3fe9190ed551e34908636411aecf228a5ff46-4442x2961-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-house-numbers-destiny",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "house-numbers-destiny"
    },
    "title": "Do House Numbers Really Shape Your Destiny?",
    "publishDate": "2025-09-02T09:30:58.286Z",
    "tags": [
      "house number numerology",
      "numerology for homes",
      "house number meaning",
      "lucky house numbers",
      "how to calculate house number numerology",
      "numerology"
    ],
    "metaDescription": "Discover what your house number means in numerology. From love to wealth, find out how your address could shape relationships, career, and energy at home.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-f1637a74f640d9b69ea22520ff2d56c7007f53bf-2592x1728-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-must-have-feng-shui-items-for-a-happier-balanced-home",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "must-have-feng-shui-items-for-a-happier-balanced-home"
    },
    "title": "Must-Have Feng Shui Items",
    "publishDate": "2025-09-02T05:45:51.393Z",
    "tags": [
      "feng shui tips",
      "feng shui for home",
      "feng shui essentials",
      "positive energy",
      "feng shui"
    ],
    "metaDescription": "Discover 8 must-have Feng Shui items—from lucky bamboo to wind chimes—that bring positive energy, harmony, and good vibes into your home.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-d89a044a0713948a323f657dabcff9383fd09135-4000x6000-jpg",
        "_type": "reference"
      }
    }
  },
  {
    "_id": "sanity-hollywood-success-fengshui",
    "_type": "article",
    "source": "sanity",
    "slug": {
      "current": "hollywood-success-fengshui"
    },
    "title": "Hollywood's Secret to Success",
    "publishDate": "2025-08-31T15:15:00.000Z",
    "tags": [
      "hollywood",
      "success",
      "wealth",
      "sanctuary",
      "kua",
      "feng shui",
      "celebrity"
    ],
    "metaDescription": "Discover how Hollywood stars like Gwyneth Paltrow, Bill Gates, and Julia Roberts use Feng Shui secrets at home to boost success, wealth, and harmony.",
    "mainImage": {
      "_type": "image",
      "asset": {
        "_ref": "image-cf6201d7302e1ed618a512bfacfca00d67573623-3958x5937-jpg",
        "_type": "reference"
      },
      "crop": {
        "_type": "sanity.imageCrop",
        "bottom": 0,
        "left": 0,
        "right": 0,
        "top": 0
      },
      "hotspot": {
        "_type": "sanity.imageHotspot",
        "height": 1,
        "width": 0.8528697771599826,
        "x": 0.4264348885799913,
        "y": 0.5
      }
    }
  }
];
